name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t yasicaaws/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true yasicaaws/react-test npm test

      - run: docker build -t yasicaaws/multi-nginx-10-14 ./nginx
      - run: docker build -t yasicaaws/multi-client-10-14 ./client
      - run: docker build -t yasicaaws/multi-server-10-14 ./server
      - run: docker build -t yasicaaws/multi-worker-10-14 ./worker

      - run: docker push yasicaaws/multi-client-10-14
      - run: docker push yasicaaws/multi-nginx-10-14
      - run: docker push yasicaaws/multi-server-10-14
      - run: docker push yasicaaws/multi-worker-10-14

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'


      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multidocker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-427058495517
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip

